SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, 
    SUM(B.PRICE * S.SALES) as TOTAL_SALES
FROM BOOK B join AUTHOR A on B.AUTHOR_ID = A.AUTHOR_ID
join BOOK_SALES S on B.BOOK_ID = S.BOOK_ID
WHERE month(S.SALES_DATE) = 1
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC