SELECT A.USER_ID, A.NICKNAME, CONCAT(A.CITY, " ", A.STREET_ADDRESS1, " ", A.STREET_ADDRESS2) as '전체주소', CONCAT(SUBSTR(A.TLNO, 1, 3), "-",                   SUBSTR(A.TLNO, 4, 4), "-", SUBSTR(A.TLNO, 8, 11)) as '전화번호'
FROM USED_GOODS_USER A
JOIN (SELECT B.USER_ID, COUNT(*) as CNT
        FROM USED_GOODS_BOARD A 
            JOIN USED_GOODS_USER B
                ON A.WRITER_ID = B.USER_ID
        GROUP BY B.USER_ID
        HAVING CNT > 2) B
ON A.USER_ID = B.USER_ID
ORDER BY A.USER_ID DESC
