select R.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, round(avg(REVIEW_SCORE), 2) as SCORE
from REST_REVIEW R 
join REST_INFO I on I.REST_ID = R.REST_ID
group by R.REST_ID
having I.ADDRESS like "서울%"
order by SCORE DESC, I.FAVORITES DESC

# SELECT A.REST_ID, B.REST_NAME, B.FOOD_TYPE, B.FAVORITES, B.ADDRESS, ROUND(AVG(A.REVIEW_SCORE),2) AS SCORE
# FROM REST_REVIEW A
# JOIN REST_INFO B ON A.REST_ID = B.REST_ID
# GROUP BY A.REST_ID
# HAVING B.ADDRESS LIKE '서울%'
# ORDER BY SCORE DESC, B.FAVORITES DESC