select R.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, round(avg(REVIEW_SCORE), 2) as SCORE
from REST_REVIEW R 
join REST_INFO I on I.REST_ID = R.REST_ID
group by R.REST_ID
having I.ADDRESS like "서울%"
order by SCORE DESC, I.FAVORITES DESC
