SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, U.GENDER, COUNT(DISTINCT S.USER_ID) as USERS
FROM USER_INFO U JOIN ONLINE_SALE S
ON U.USER_ID = S.USER_ID
WHERE U.GENDER is not null
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), U.GENDER
ORDER BY YEAR, MONTH, U.GENDER