SELECT B.APNT_NO, C.PT_NAME, B.PT_NO, A.MCDP_CD, A.DR_NAME, B.APNT_YMD
FROM DOCTOR A JOIN (
    SELECT APNT_NO, PT_NO, MDDR_ID, APNT_YMD
    FROM APPOINTMENT 
    WHERE MCDP_CD = 'CS' AND APNT_CNCL_YN = 'N'
    HAVING DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13') B ON A.DR_ID = B.MDDR_ID
    JOIN PATIENT C ON B.PT_NO = C.PT_NO
ORDER BY B.APNT_YMD