SELECT A.EMP_NO, A.EMP_NAME, 
CASE 
    WHEN AVG(B.SCORE) >= 96 THEN "S"
    WHEN AVG(B.SCORE) >= 90 and AVG(B.SCORE) < 96 THEN "A"
    WHEN AVG(B.SCORE) >= 80 and AVG(B.SCORE) < 90 THEN "B"
    ELSE "C"
END as GRADE,
CASE
    WHEN AVG(B.SCORE) >= 96 THEN A.SAL * 0.2
    WHEN AVG(B.SCORE) >= 90 and AVG(B.SCORE) < 96 THEN A.SAL * 0.15
    WHEN AVG(B.SCORE) >= 80 and AVG(B.SCORE) THEN A.SAL * 0.1
    ELSE 0
END as BONUS
FROM HR_EMPLOYEES A JOIN HR_GRADE B ON A.EMP_NO = B.EMP_NO
GROUP BY A.EMP_NO
ORDER BY A.EMP_NO