WITH A AS (
    SELECT EMP_NO, SUM(SCORE) as SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
)

SELECT A.SCORE, A.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM HR_EMPLOYEES B JOIN A on B.EMP_NO = A.EMP_NO